### PR TITLE
Master upstream dev 20170508

### PR DESCRIPTION
**Pull request by mbolivar**

### CODE REVIEW

**Review by mike-scott — CHANGES_REQUESTED** [review]
Can we:
- add flash_base to the boot_rsp structure and set it once where it would be available later so we don't call flash_device_base() 3 times?
- or adjust rsp.br_image_off early on, so that it's correct later (and eliminate the later calls)

**Comment by mbolivar** [comment]
> Can we:
> 
>     - add flash_base to the boot_rsp structure and set it once where it would be available later so we don't call flash_device_base() 3 times?
>     - or adjust rsp.br_image_off early on, so that it's correct later (and eliminate the later calls)

Do you mean writing flash_device_base() in three places, or calling it three times at runtime? We only ever call it once at runtime, but there are multiple places in the codebase that need to know the address when they get a boot response.

The feeling I got from upstream is that they want to keep the code which deals with base addresses out of the library as much as possible, to keep that code written in terms of offsets. That makes it easier to test in the simulator, etc.

I've posted this commit as https://github.com/runtimeco/mcuboot/pull/49/commits/736e446f080651f2bc6fc013f0037763bb813976 in an upstream PR -- I'll copy your comment there and see what people think.

**Comment by mbolivar** [comment]
> or adjust rsp.br_image_off early on, so that it's correct later (and eliminate the later calls)

Something similar to this was proposed by the mcuboot developers in response to an RFC, but it has the same problem: it's treating an offset as if it were an address.

**Review by mike-scott — APPROVED** [review]
A lot of this needs to go upstream.  But as long as you're dealing with the details on mcuboot review, I'm ok with this being merged for now.

**Review by rsalveti — APPROVED** [review]
Fine with the changes (nothing really major), but I do expect that a few patches might take a few iterations with upstream (besides updating the simulator).

**Comment by doanac** [comment]
simulator works again. Thanks!

**Comment by mbolivar** [comment]
I'm glad! More changes are in the pipe but that's good to know.

On May 18, 2017 2:28 PM, "Andy Doan" <notifications@github.com> wrote:

simulator works again. Thanks!

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Linaro/mcuboot/pull/6#issuecomment-302502345>, or mute
the thread

**Pull request merged**
